### ISSUE TITLE
Publish to RubyGems

### ISSUE THREAD

**Issue by ghost** [rubinius/rubinius-docs#1]
It would make installation easier if `gem install rubinius-docs` worked.

**Comment by brixen** [comment]
I do want it to work, just haven't gotten to it yet. Curious why you closed the issue?

**Comment by ghost** [comment]
I closed it because I thought @dbussink told me docs were now in the rubinius.github.io repo; perhaps I misunderstood.

**Comment by brixen** [comment]
Ah ok, I understand now. Sorry, it's a bit confusing. Yes, the http://rubini.us site is the rubinius.github.io repo. But this gem will be the offline version of that suitable to install via rubygems. It will have some support code as well, so it seemed reasonable to have a proper repo for it.

I'll reopen this to keep it on my radar. Just need a few more things.
